dist: bionic
language: c

branches:
  only:
    - master

jobs:
    - name: "Build with LLVM/Clang 7"
      env:
      - MATRIX_EVAL="CC=clang CXX=clang++"

    - name: "Build with LLVM/Clang 9"
      addons:
        apt:
          packages:
          - clang-9
      env:
      - MATRIX_EVAL="CC=clang-9 CXX=clang++-9"

    - name: "Build with LLVM/Clang 10"
      addons:
        apt:
          sources:
          - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
          key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
          - clang-10
      env:
      - MATRIX_EVAL="CC=clang-10 CXX=clang++-10"

    - name: "Build with GCC 7.4"
      env:
      - MATRIX_EVAL="CC=gcc CXX=g++"

    - name: "Build with GCC 9"
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-9
          - g++-9
      env:
      - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"

    - name: "Build with GCC 10"
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-10
          - g++-10
      env:
      - MATRIX_EVAL="CC=gcc-10 CXX=g++-10"

before_script: 
- cmake --version
- eval "${MATRIX_EVAL}"
- $CC --version
- $CXX --version

script:
- mkdir ./build
- cd ./build
- cmake ..
- cmake --build .
- cd ..
