name: Project build

on:
  workflow_run:
    workflows: [Docker build]
    types: [completed]

jobs:
  project_build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andymender/raylib_base:latest
    permissions:
      packages: read
      contents: read
    strategy:
      matrix:
        compilers:
          - 'CC=clang-20 CXX=clang++-20'
          - 'CC=gcc-12 CXX=g++-12'
          - 'CC=gcc-13 CXX=g++-13'
          - 'CC=gcc-14 CXX=g++-14'
    steps:
      # NOTE: Required step!
      - name: Do repository checkout
        uses: actions/checkout@v5
      - name: Build project
        run: |
          echo "Starting build..."
          ${{ matrix.compilers }} cmake -S . -B build
