name: Project build

on:
  # TODO: Limit base container rebuilds to "on-demand"?
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  project_build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andymender/raylib_base:latest
    permissions:
      packages: read
      contents: read
    steps:
      # NOTE: Required step!
      - name: Do repository checkout
        uses: actions/checkout@v5
    
      - name: Build project
        run: |
            echo "Starting build..."
 